# Jekyll configuration
# http://jekyllrb.com/docs/home/

name: C37 - CNC
description: C37 - CNC website
author:
  name: C37 Team

source: src
destination: www

url: http://beta.c37.co
atom_path: /blog/atom.xml

timezone: America/Sao_Paulo

# http://jekyllrb.com/docs/permalinks/
permalink: /blog/:categories/:year/:month/:day/:title.html

markdown: kramdown
#markdown: redcarpet


regeneration: true

#highlighter: pygments

paginate: 8
paginate_path: "/blog/page:num/"

gems: [jekyll-paginate]
